### ISSUE TITLE
Parallel fox 

### ISSUE THREAD

**Issue by codiclimited1** [VFPX/ParallelFox#2]
Am getting the following error:-

EXECUTING PROGRAM NAME: SCREEN.PARPOOLMGR.CREATEPARAMETEROBJECT

PROGRAM LINE NUMBER: 23

ERROR MESSAGE: Incorrect property name.

PROGRAM CODE: .F.

when executing the following library

7 -- PROCEDURE SCREEN.PARPOOLMGR.CREATEPARAMETEROBJECT C:\CMIS\XSMS4\PARALLELFOX.VCT

Kindly help

**Comment by JoelLeach** [comment]
Could you provide code you are using the call your program with ParallelFox?

**Comment by codiclimited1** [comment]
[stepsa.txt](https://github.com/VFPX/ParallelFox/files/3246150/stepsa.txt)
This is a program extracted from steps_after.prg. 
Please help on the following:-
1. Parallel.StartWorkers("\vcmis\prgs\tt.prg",,.t.)	&& ok - how do i suppress debugging
2. Parallel.StartWorkers("\vcmis\prgs\tt.prg")		&& when not in development - but prog hangs
3. SET DEFAULT TO \cmis\dbfs	&& work place where tables are - parallelfox.vcx misses

**Comment by codiclimited1** [comment]
https://github.com/VFPX/ParallelFox/files/3246150/stepsa.txt
This is a program extracted from steps_after.prg.
Please help on the following:-

Parallel.StartWorkers("\vcmis\prgs\tt.prg",,.t.)	&& ok - how do i suppress debugging
Parallel.StartWorkers("\vcmis\prgs\tt.prg")	&& when not in development - but prog hangs
SET DEFAULT TO \cmis\dbfs	&& work place where tables are - parallelfox.vcx misses

**Comment by tuansieucap** [comment]
I run steps_after.prg file. This file is not in development mode. It does not have ,,.t. like this: Parallel.StartWorkers(FullPath("Steps_After.prg"))

In parallelfox.vcx -> workerproxy -> Init function, this like of code (This.oApplication = CreateObject("ParallelFox.Application")) causes a following error:  "Class definition ParallelFox.APPLICATION is not found".

I change the line of code to: This.oApplication = CreateObject("ParallelFox.WorkerMgr")

Then this line of code loVFP = This.oApplication.VFP does not work. I remove it.

Then this line of code (This.oWorker.SendCommand(loCommand)) shows an error below:

![image](https://user-images.githubusercontent.com/103373221/162688309-68b4c706-04f4-48f4-b40b-11868411bf20.png)

It looks like the code not in development mode does not work. How do we fix this issue?

**Comment by JoelLeach** [comment]
I must have overlooked this issue, and I apologize for that.  I'm still not certain what caused this problem.  I'd first say try it with the latest version 1.3 and make sure to follow installation instructions at https://github.com/VFPX/ParallelFox#installation and the Help file.  Beyond that, when not running in debug mode, the first parameter to StartWorkers() will usually be an APP/EXE that has ParallelFox.vcx compiled into it.  If you want to use PRG, you may have to set paths so that ParallelFox.vcx code can be found.  I'm closing this now due to the age of the issue, but feel free to reopen or open a new issue if the problem persists.
