### ISSUE TITLE
ParallelFox 1.2 having issue with UAC

### ISSUE THREAD

**Issue by IrwinAsh** [VFPX/ParallelFox#3]
Does anyone know how to get past User Access Control not allowing execution of ParallelFox

**Comment by ThorstenDoherr** [comment]
Does UAC not allow the adjustments to the registry to register ParallelFox or does it block the execution even after properly registering the OLE object? 
Does this also affect the debug mode?
Sorry, for only having questions instead of answers but your post is quite vague. I assume that deactivating UAC is not the right answer.
By the way, I am a big fan of ParallelFox. It really has a huge impact on performance and is relatively easy to implement. If you are interested, I have written a ParallelFoxWrapper (see: SearchEngine/code/modul/custom.prg) that automatizes the whole ParallelFox deployment incl. installation, calls, fallback to debug mode (if something goes awry, e.g. the UAC) and so on.

**Comment by JoelLeach** [comment]
ParallelFox.exe does not require elevation and it should not be triggering a UAC dialog. I would go into the properties of ParallelFox.exe and look at the Compatibility tab.  If you find it has been inadvertently set to run as administrator or in compatibility mode, uncheck those boxes.

**Comment by IrwinAsh** [comment]
Thanks Joel!

Irwin Ash

**Comment by IrwinAsh** [comment]
Thanks Thorsten

I am also big fan
Sorry about being vague

Correct, turning off UAC is not the desired solution

Thanks again



Irwin Ash

**Comment by IrwinAsh** [comment]
Thanks everyone for your help

turns out issue was i was always registering ParallelFox.exe and i fixed by using IsRegistered() and only registering if required. Probably will still get UAC but at least it will only be once

 thanks again

**Comment by JoelLeach** [comment]
Glad to hear you resolved it.
